SELECT @@UNIQUE_CHECKS, @@FOREIGN_KEY_CHECKS; -- Print state of UNIQUE_CHECKS and FOREIGN_KEY_CHECKS before updates
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;


-- TODO: put commands here


SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SELECT @@UNIQUE_CHECKS, @@FOREIGN_KEY_CHECKS; -- Print state of UNIQUE_CHECKS and FOREIGN_KEY_CHECKS after updates